name: msys2
# msys2 build for jbig2enc - head from master branch.

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: MINGW64
            mingw_package_prefix: mingw-w64-x86_64

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v5
      with:
        python-version: 'pypy3.12'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ${{ matrix.msystem }}
        install: autoconf automake automake-wrapper git libtool make
    - run: pacman --noconfirm -S ${{ matrix.mingw_package_prefix }}-gcc
    - run: gcc --version
